
package com.example.api_gateway.soap.coursews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseService", targetNamespace = "http://service.course.soa.university.com/", wsdlLocation = "http://localhost:5050/course-service/services/course?wsdl")
public class CourseService_Service
    extends Service
{

    private final static URL COURSESERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSESERVICE_EXCEPTION;
    private final static QName COURSESERVICE_QNAME = new QName("http://service.course.soa.university.com/", "CourseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5050/course-service/services/course?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSESERVICE_WSDL_LOCATION = url;
        COURSESERVICE_EXCEPTION = e;
    }

    public CourseService_Service() {
        super(__getWsdlLocation(), COURSESERVICE_QNAME);
    }

    public CourseService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSESERVICE_QNAME, features);
    }

    public CourseService_Service(URL wsdlLocation) {
        super(wsdlLocation, COURSESERVICE_QNAME);
    }

    public CourseService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSESERVICE_QNAME, features);
    }

    public CourseService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseService
     */
    @WebEndpoint(name = "CourseServicePort")
    public CourseService getCourseServicePort() {
        return super.getPort(new QName("http://service.course.soa.university.com/", "CourseServicePort"), CourseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseService
     */
    @WebEndpoint(name = "CourseServicePort")
    public CourseService getCourseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.course.soa.university.com/", "CourseServicePort"), CourseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSESERVICE_EXCEPTION!= null) {
            throw COURSESERVICE_EXCEPTION;
        }
        return COURSESERVICE_WSDL_LOCATION;
    }

}
