
package com.example.api_gateway.soap.coursews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CourseService", targetNamespace = "http://service.course.soa.university.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CourseService {


    /**
     * 
     * @param course
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCourse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.CreateCourse")
    @ResponseWrapper(localName = "createCourseResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.CreateCourseResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/createCourseRequest", output = "http://service.course.soa.university.com/CourseService/createCourseResponse")
    public CourseResponse createCourse(
        @WebParam(name = "course", targetNamespace = "")
        Course course);

    /**
     * 
     * @param courseId
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCourseById", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCourseById")
    @ResponseWrapper(localName = "getCourseByIdResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCourseByIdResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getCourseByIdRequest", output = "http://service.course.soa.university.com/CourseService/getCourseByIdResponse")
    public CourseResponse getCourseById(
        @WebParam(name = "courseId", targetNamespace = "")
        Long courseId);

    /**
     * 
     * @param courseCode
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCourseByCode", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCourseByCode")
    @ResponseWrapper(localName = "getCourseByCodeResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCourseByCodeResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getCourseByCodeRequest", output = "http://service.course.soa.university.com/CourseService/getCourseByCodeResponse")
    public CourseResponse getCourseByCode(
        @WebParam(name = "courseCode", targetNamespace = "")
        String courseCode);

    /**
     * 
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCourses", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetAllCourses")
    @ResponseWrapper(localName = "getAllCoursesResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetAllCoursesResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getAllCoursesRequest", output = "http://service.course.soa.university.com/CourseService/getAllCoursesResponse")
    public CourseListResponse getAllCourses();

    /**
     * 
     * @param semester
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCoursesBySemester", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCoursesBySemester")
    @ResponseWrapper(localName = "getCoursesBySemesterResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCoursesBySemesterResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getCoursesBySemesterRequest", output = "http://service.course.soa.university.com/CourseService/getCoursesBySemesterResponse")
    public CourseListResponse getCoursesBySemester(
        @WebParam(name = "semester", targetNamespace = "")
        String semester);

    /**
     * 
     * @param professorId
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCoursesByProfessor", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCoursesByProfessor")
    @ResponseWrapper(localName = "getCoursesByProfessorResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCoursesByProfessorResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getCoursesByProfessorRequest", output = "http://service.course.soa.university.com/CourseService/getCoursesByProfessorResponse")
    public CourseListResponse getCoursesByProfessor(
        @WebParam(name = "professorId", targetNamespace = "")
        Long professorId);

    /**
     * 
     * @param course
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCourse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.UpdateCourse")
    @ResponseWrapper(localName = "updateCourseResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.UpdateCourseResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/updateCourseRequest", output = "http://service.course.soa.university.com/CourseService/updateCourseResponse")
    public CourseResponse updateCourse(
        @WebParam(name = "course", targetNamespace = "")
        Course course);

    /**
     * 
     * @param courseId
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCourse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.DeleteCourse")
    @ResponseWrapper(localName = "deleteCourseResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.DeleteCourseResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/deleteCourseRequest", output = "http://service.course.soa.university.com/CourseService/deleteCourseResponse")
    public CourseResponse deleteCourse(
        @WebParam(name = "courseId", targetNamespace = "")
        Long courseId);

    /**
     * 
     * @param schedule
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSchedule", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.AddSchedule")
    @ResponseWrapper(localName = "addScheduleResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.AddScheduleResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/addScheduleRequest", output = "http://service.course.soa.university.com/CourseService/addScheduleResponse")
    public CourseResponse addSchedule(
        @WebParam(name = "schedule", targetNamespace = "")
        Schedule schedule);

    /**
     * 
     * @param schedule
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSchedule", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.UpdateSchedule")
    @ResponseWrapper(localName = "updateScheduleResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.UpdateScheduleResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/updateScheduleRequest", output = "http://service.course.soa.university.com/CourseService/updateScheduleResponse")
    public CourseResponse updateSchedule(
        @WebParam(name = "schedule", targetNamespace = "")
        Schedule schedule);

    /**
     * 
     * @param scheduleId
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSchedule", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.DeleteSchedule")
    @ResponseWrapper(localName = "deleteScheduleResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.DeleteScheduleResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/deleteScheduleRequest", output = "http://service.course.soa.university.com/CourseService/deleteScheduleResponse")
    public CourseResponse deleteSchedule(
        @WebParam(name = "scheduleId", targetNamespace = "")
        Long scheduleId);

    /**
     * 
     * @param courseId
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCourseSchedules", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCourseSchedules")
    @ResponseWrapper(localName = "getCourseSchedulesResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetCourseSchedulesResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getCourseSchedulesRequest", output = "http://service.course.soa.university.com/CourseService/getCourseSchedulesResponse")
    public CourseResponse getCourseSchedules(
        @WebParam(name = "courseId", targetNamespace = "")
        Long courseId);

    /**
     * 
     * @param searchTerm
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchCourses", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.SearchCourses")
    @ResponseWrapper(localName = "searchCoursesResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.SearchCoursesResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/searchCoursesRequest", output = "http://service.course.soa.university.com/CourseService/searchCoursesResponse")
    public CourseListResponse searchCourses(
        @WebParam(name = "searchTerm", targetNamespace = "")
        String searchTerm);

    /**
     * 
     * @return
     *     returns com.example.api_gateway.soap.coursews.CourseListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableCourses", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetAvailableCourses")
    @ResponseWrapper(localName = "getAvailableCoursesResponse", targetNamespace = "http://service.course.soa.university.com/", className = "com.example.api_gateway.soap.coursews.GetAvailableCoursesResponse")
    @Action(input = "http://service.course.soa.university.com/CourseService/getAvailableCoursesRequest", output = "http://service.course.soa.university.com/CourseService/getAvailableCoursesResponse")
    public CourseListResponse getAvailableCourses();

}
